# Generated by Django 2.2.6 on 2019-10-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=500)),
                ('holding_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantsCompetitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievements', models.TextField(blank=True, max_length=1000)),
                ('biography', models.TextField(blank=True, max_length=3000)),
                ('interesting_facts', models.TextField(blank=True, max_length=1000)),
                ('name', models.TextField(blank=True, max_length=100)),
                ('second_name', models.TextField(blank=True, max_length=100)),
                ('surname', models.TextField(blank=True, max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('competitions', models.ManyToManyField(to='SportProg.Competitions')),
            ],
        ),
    ]
