# Generated by Django 2.2.6 on 2019-10-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportProg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantscompetitions',
            name='competitions',
        ),
        migrations.AddField(
            model_name='competitions',
            name='participants',
            field=models.ManyToManyField(related_name='related_competitions', to='SportProg.ParticipantsCompetitions'),
        ),
    ]
