# Generated by Django 2.2.6 on 2019-10-08 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SportProg', '0002_auto_20191006_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('second_name', models.TextField(max_length=100)),
                ('surname', models.TextField(max_length=100)),
                ('birth_date', models.DateField()),
                ('job_start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VideoPlots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('production_date', models.DateField()),
                ('authors', models.ManyToManyField(related_name='related_video_plots', to='SportProg.Employees')),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportProg.Positions'),
        ),
    ]
